name: Deploy to Development

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to Development Server
        run: |
          cd ~/workspace/env
          git pull
          ./army/update.sh dev
